version: "3.9"
networks:
  api_network:
    driver: bridge
services:
  csdt_neo4j:
    image: neo4j:3.5.3
    hostname: csdt_neo4j
    container_name: csdt_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=${CSDT_USER}/${CSDT_PASSWORD}
    networks:
      - api_network
  web:
    image: product-search-api
    build:
      dockerfile: Dockerfile.web
    env_file:
      - env_file
    depends_on:
      - csdt_neo4j
    networks:
      - api_network
    ports:
      - "80:8181"